#pragma once

#define FARM_FOOD_GENERATION 5
#define FARM_WOOD_GENERATION 0
#define FARM_STONE_GENERATION 0

#define LUMBER_FOOD_GENERATION 0
#define LUMBER_WOOD_GENERATION 5
#define LUMBER_STONE_GENERATION 0

#define QUARRY_FOOD_GENERATION 0
#define QUARRY_WOOD_GENERATION 0
#define QUARRY_STONE_GENERATION 5
